# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['team@listeat.io']

    #bin/console doctrine:database:create

    #bin/console doctrine:database:create
